### ISSUE TITLE
Configurable server address

### ISSUE THREAD

**Issue by luciopaiva** [luciopaiva/witchcraft#10]
Allow specifying a custom server address and port.

**Comment by schmijos** [comment]
I'd especially be interested in loading scripts from Github Pages.

**Comment by luciopaiva** [comment]
Hi @schmijos this feature was now released as part of v2.6.0. You should be able to change the server address via the popup when you click the witch icon in the toolbar. Can be either local or remote.

I am closing the ticket, but please let me know if you have any problems.
