### ISSUE TITLE
feature request: global scripts

### ISSUE THREAD

**Issue by mjuksel** [luciopaiva/witchcraft#11]
Could you add global scripts to this project ?
im thinking universal themes, overlays everywhere etc :octocat: 
love the concept !

**Comment by luciopaiva** [comment]
Hmm, that should be easy to do. I just don't know what name to give to that script. `global.js`? Ideally, it shouldn't conflict with any valid domain. I see that `global` is a [valid TLD](https://en.wikipedia.org/wiki/.global), so let's not use it. I'm inclined to prefix it with some character that can't be used in domain names, like `_`. Maybe `_global.js`? That's not a bad name. It will appear on top of other scripts when alphabetically listing the directory and also makes it clear its purpose. Looks good to me? What do you think?

**Comment by luciopaiva** [comment]
And, of course, also `_global.css`.

**Comment by mjuksel** [comment]
Exactly what i was thinking !

_global sounds good to me :)

**Comment by luciopaiva** [comment]
Alright, done :-)

I have just released version 2.3.0 to the Chrome store. It may take up to 60 minutes for the publishing to complete.

Thanks for your suggestion, @mjuksel.
