### ISSUE TITLE
Unclear folder location

### ISSUE THREAD

**Issue by romgrk** [luciopaiva/witchcraft#12]
After 5 minutes of reading docs, I still don't know which folder the files must be put in.

**Comment by luciopaiva** [comment]
I need to iterate a few more times through the docs to make it easier to understand.

You can put your files in any folder you want (in my case, I use `~/.witchcraft`). In the end, it just needs to match whatever you pass to *Web Server for Chrome* when you click the `CHOOSE FOLDER` button (see screenshot [here](http://localhost:63342/witchcraft/docs/how-to-install.html)).

I'll try and make the docs clearer when I have the time. Thanks for you feedback, @romgrk.

**Comment by luciopaiva** [comment]
Hey @romgrk,

I have rewritten the installation steps to make it more complete and also removed unnecessary information. Now there's also a FAQ page and I put your question there as well. I am closing this issue as done, but feel free to reopen it if you think the docs could improved even further.

Please see new instructions here: https://luciopaiva.com/witchcraft/how-to-install.html

Thanks!
