### ISSUE TITLE
Possibility to enable/disable scripts

### ISSUE THREAD

**Issue by schmijos** [luciopaiva/witchcraft#13]
We at our company would like to manage all our scripts together in one repository. How could we get some individual configuration per user? Now a fork of the repo is the only possibility.

**Comment by schmijos** [comment]
Cool! Thank you very much for your input. I already had a similar idea, but rejected it because you would have to include this piece of checking-code in all the scripts, right? Is there a possibility to use partials? Maybe to include a config file loaded from the same web server which is serving the assets anyways?

**Comment by luciopaiva** [comment]
Actually, it is possible :tada: 
There's an `@include` command you can use exactly for that. Say you create a use configuration script named `user-config.js`:

```javascript
function loadUserConfiguration() {
    // ToDo get it from local storage
}
```

And then include it in your scripts like this:

```javascript
// @include user-config.js

const userConfig = loadUserConfiguration();
```

You can use `@include` anywhere in your code, not just at the beginning. You can also include as many scripts as you want and those scripts can include others recursively. Remember to always put it in a single line comment.

Alternatively, you could also put it in `_global.js`, which a special script that gets loaded for every page, but `@include` probably makes more sense in this case.

**Comment by schmijos** [comment]
Since our people can use *git*, I ended up with the following `_config.js`:

```
const config =
  // @include .config.json
;

function callIfEnabled(configKey, callback) {
  if(config[configKey]) {
    callback();
  }
}
```

This also enables me to do my own error handling (e.g. sending a report to *Sentry*).

The config is then used in each file like that:

```
// @include _config.js
callIfEnabled('sentry.io', function() {
  …
});
```
