### ISSUE TITLE
use jquery with witchcraft?

### ISSUE THREAD

**Issue by johnJeff55** [luciopaiva/witchcraft#16]
I'm loving witchcraft so far!

I'd like to use jquery in my witchcraft js files. Is this possible?
___

**EDIT**: Dang! Another classic RTFM blunder on my part...! :p 

Found the answer at: https://github.com/luciopaiva/witchcraft/pull/9/files

Sorry: I can't figure out how to delete my question here... so I've just updated it to include the answer.

~Jeff.

**Comment by luciopaiva** [comment]
Hey @johnJeff55, no problem! 

Sorry I took so long to answer back, it's been a bit busier than usual here these past weeks.

Great that you solved it :-)

**Comment by luciopaiva** [comment]
Btw @johnJeff55, I noticed the blunder was actually on my part, since that documentation you found is buried in an old commit. I have just rewritten part of the home page to include more information on how to use Witchcraft and also added your question to the FAQ. Thanks for pointing that out!

**Comment by johnJeff55** [comment]
Thanks @luciopaiva. Glad I could help! :) I’m very keen on Witchcraft –
especially as a tool to give visually-impaired people fine-grained,
site-by-site control of their browser displays. (Please see my Witchcraft
review on your Chrome-Store page. :)

I’d be happy to help move the Witchcraft project forward – with additional
documentation, demo’s, promo, ‘help-desk’ functions & other such
donkey-work… and I’d be downright ecstatic if it turned out that the
possibility of a deeper (project) dive into Witchcraft's ‘visually-impaired
use-case’ potentials captured your imagination! :)

(Both my family situation, and my previous experience as a project/grant
development consultant to ngo’s in Canada strongly suggest that you’re
really onto something here... I mean, something that might really matter to
real people in their day-to-day lives!)

Anyway, thanks again for your ‘Btw’ response, and please let me know if
you’d like to explore some of the possibilities here.

Best regards,

Jeff.
