### ISSUE TITLE
Quick item... code example on your homepage

### ISSUE THREAD

**Issue by hierozbosch** [luciopaiva/witchcraft#26]
Hey, the code example on your home page appears to have a typo in the JS.  Isn't that supposed to be:
window.addEventListener("load", () => {   });

This is what I copied from the witchcraft homepage that didn't work:

window.addEventListener("load" => () {
    document.querySelectorAll("img")
        .forEach(img => img.style.transform = "scaleX(-1)");
});

Thanks for the extension!  Looks like it's going to work for highlighting critical incoming emails for me.

**Comment by luciopaiva** [comment]
Nice catch, @hierozbosch! 
It's fixed now, thanks for letting me know.
