### ISSUE TITLE
The js and css modification is not being picked up by the extension without reloading the page

### ISSUE THREAD

**Issue by powpowshen** [luciopaiva/witchcraft#31]
I noticed the modification is not being picked up by the extension without reloading the page. In the [official page](https://luciopaiva.com/witchcraft/), the feature is described as below.
_Script changes are seamless
Whenever you edit or create new scripts, there's no need to reload anything other than the page where the scripts are supposed to run. This is what makes Witchcraft special and different from other popular scripting tools, like Greasemonkey or Tampermonkey;_

I also don't see how can this be done without polling or websocket in the source code. Have I misunderstood this feature?

**Comment by mjuksel** [comment]
As you quoted, it says it needs a page reload.

It just says there's no need for manually reloading anything else like webservers, or chrome extension or any settings/program you can think of 👍

**Comment by powpowshen** [comment]
I see. It does say page reload is needed. Thank you for the clarification.

**Comment by Glaived** [comment]
You can launch a proxy server via [browser-sync](https://browsersync.io) to do local development with hot realoding.

e.g: `browser-sync 'https://www.google.com/' --listen 'localhost' --files '**/*.css, **/*.js' --no-inject-changes`
