### ISSUE TITLE
File path resolution?

### ISSUE THREAD

**Issue by earthsuit0** [luciopaiva/witchcraft#46]
Just a simple user here. I'm trying to get a script to load for "http://trisphere.net/inventory.php".  My script folder is "trisphere" and the scripts are "inventory.user.js" and the same script renamed as "inventory.js". Neither of them will load. Help?

**Comment by mjuksel** [comment]
Try `www.trisphere.net` as folder name, I had to add `www.` to a couple domains.

**Comment by earthsuit0** [comment]
Thank you for the reply. There was no joy with this. Could it be my folder location? 

users/ron/my games/www.trisphere.net

I'd think that would be resolved while navigating to the folder via the webserver. When the page is loaded, the icon shows there are no scripts loaded though it has access to the site.

**Comment by luciopaiva** [comment]
Hey @earthsuit0,

I just had the chance to test it here. I tried a folder called `trisphere.net` with a script inside called `index.php.js` and it worked fine when I tried `trisphere.net/index.php`. I couldn't try `inventory.php` because it looks like I need an account and the page just redirects me to `index.php`.

Does your local web server root correctly point to `users/ron/documents/my games`?

**Comment by earthsuit0** [comment]
The local server does point to `users/ron/documents/my games/www.trisphere.net`. The correct .js files list when I click on the ip address. I tried renaming the script `inventory.php.js`, instead of `inventory.user.js`, but it still does not work.

I'm sorry for taking up so much of your time. I'm sure I'm just making some silly mistake.

**Comment by luciopaiva** [comment]
This might be your problem: the server folder should be `users/ron/documents/my games/`, not `users/ron/documents/my games/www.trisphere.net`.

**Comment by earthsuit0** [comment]
Unfortunately, neither of these recommendations resolved the issue. It's not really a big deal; just a very old game to spend some time on. Please don't give it another thought. Thank you for your time though.

**Comment by luciopaiva** [comment]
No problem! Please let me know if you find out what is wrong.

**Comment by mbrk-rio** [comment]
user:defunkt ubuntu
